#!/usr/bin/env bash
_CONFIG_CONF="/etc/fusionpbx/config.conf"

_DB_HOST=$(awk -F "=" '/database.0.host/ {print $2}' "${_CONFIG_CONF}" | tr -d ' ')
_DB_PORT=$(awk -F "=" '/database.0.port/ {print $2}' "${_CONFIG_CONF}" | tr -d ' ')
_DB_NAME=$(awk -F "=" '/database.0.name/ {print $2}' "${_CONFIG_CONF}" | tr -d ' ')
_DB_USERNAME=$(awk -F "=" '/database.0.username/ {print $2}' "${_CONFIG_CONF}" | tr -d ' ')
_DB_PASSWORD=$(awk -F "=" '/database.0.password/ {print $2}' "${_CONFIG_CONF}" | tr -d ' ')

export PGPASSWORD=${_DB_PASSWORD}

query () {
# Check if parameter is provided
    if [ -z "$1" ]; then
        #echo "Usage: execute_psql_command <SQL_COMMAND>"
        return 1
    fi
    PAGER="" psql -h "${_DB_HOST}" -p "${_DB_PORT}" -d "${_DB_NAME}" -U "${_DB_USERNAME}" -n -w -c "${1}"
}

index () {
    _TABLE=${1}
    _FIELD=${2}
    if [ -z ${3} ]; then
        _INDEX="${_TABLE}_${_FIELD}"
    else
        _INDEX=${3}
    fi
    query "CREATE INDEX ${_INDEX} on ${_TABLE} (${_FIELD});"
}

query "CREATE INDEX v_xml_cdr_domain_uuid_fkey ON v_xml_cdr (domain_uuid)"
query "CREATE INDEX v_xml_cdr_billsec ON v_xml_cdr (billsec)"
query "CREATE INDEX v_xml_cdr_caller_id_name ON v_xml_cdr (caller_id_name)"
query "CREATE INDEX v_xml_cdr_destination_number ON v_xml_cdr (destination_number)"
query "CREATE INDEX v_xml_cdr_duration ON v_xml_cdr (duration)"
query "CREATE INDEX v_xml_cdr_hangup_cause ON v_xml_cdr (hangup_cause)"
query "CREATE INDEX v_xml_cdr_start_stamp ON v_xml_cdr (start_stamp)"
query "CREATE INDEX v_xml_cdr_start_epoch ON v_xml_cdr  (start_epoch)"
query "CREATE INDEX v_xml_cdr_direction ON v_xml_cdr (direction)"
query "CREATE INDEX v_xml_cdr_extension_uuid_fkey ON v_xml_cdr  (extension_uuid)"
query "CREATE INDEX v_xml_cdr_accountcode ON v_xml_cdr  (accountcode)"
query "CREATE INDEX v_xml_cdr_context ON v_xml_cdr (context)"
query "CREATE INDEX v_xml_cdr_end_epoch ON v_xml_cdr (end_epoch)"
query "CREATE INDEX v_xml_cdr_network_addr ON v_xml_cdr (network_addr)"
query "CREATE INDEX v_xml_cdr_answer_stamp ON v_xml_cdr (answer_stamp)"
query "CREATE INDEX v_xml_cdr_end_stamp ON v_xml_cdr (end_stamp)"
query "CREATE INDEX v_xml_cdr_bridge_uuid ON v_xml_cdr (bridge_uuid)"
query "CREATE INDEX v_xml_cdr_caller_id_number ON v_xml_cdr (caller_id_number)"
query "CREATE INDEX v_xml_cdr_call_center_queue_uuid ON v_xml_cdr (call_center_queue_uuid)"
query "CREATE INDEX v_xml_cdr_originating_leg_uuid ON v_xml_cdr (originating_leg_uuid)"
query "CREATE INDEX v_xml_cdr_cc_side ON v_xml_cdr (cc_side)"
query "CREATE INDEX v_extensions_domain_uuid_fkey ON v_extensions (domain_uuid)"
query "CREATE INDEX v_extensions_extensions_enabled ON v_extensions (enabled)"
query "CREATE INDEX v_extensions_number_alias ON v_extensions (number_alias)"
query "CREATE INDEX v_extensions_extensions_extension ON v_extensions (extension)"
query "CREATE INDEX v_dialplans_domain_uuid_fkey ON v_dialplans (domain_uuid)"
query "CREATE INDEX v_dialplans_app_uuid ON v_dialplans (app_uuid)"
query "CREATE INDEX v_dialplans_dialplan_context ON v_dialplans (dialplan_context)"
query "CREATE INDEX v_dialplans_dialplan_order ON v_dialplans (dialplan_order)"
query "CREATE INDEX v_dialplans_dialplan_enabled ON v_dialplans (dialplan_enabled)"
query "CREATE INDEX v_dialplans_dialplan_details_domain_uuid_fkey ON v_dialplan_details (domain_uuid)"
query "CREATE INDEX v_dialplans_dialplan_uuid_fkey ON v_dialplan_details (dialplan_uuid)"
query "CREATE INDEX v_dialplans_dialplan_detail_order ON v_dialplan_details (dialplan_detail_order)"
query "CREATE INDEX v_domains_domain_name ON v_domains (domain_name)"
query "CREATE INDEX v_domains_domain_description ON v_domains (domain_description)"
query "CREATE INDEX v_domains_domain_parent_uuid_fkey ON v_domains (domain_parent_uuid)"
query "CREATE INDEX v_domains_domain_enabled ON v_domains (domain_enabled)"
query "CREATE INDEX v_destinations_domain_uuid_fkey ON v_destinations (domain_uuid)"
query "CREATE INDEX v_destinations_destination_type ON v_destinations (destination_type)"
query "CREATE INDEX v_destinations_destination_number ON v_destinations (destination_number)"
query "CREATE INDEX v_destinations_destination_enabled ON v_destinations (destination_enabled)"
query "CREATE INDEX v_users_domain_uuid_fkey ON v_users (domain_uuid)"
query "CREATE INDEX v_users_username ON v_users (username)"
query "CREATE INDEX v_users_password ON v_users (password)"
query "CREATE INDEX v_users_contact_uuid_fkey ON v_users (contact_uuid)"
query "CREATE INDEX v_users_user_status ON v_users (user_status)"
query "CREATE INDEX v_users_user_enabled ON v_users (user_enabled)"
query "CREATE INDEX v_devices_domain_uuid_fkey ON v_devices (domain_uuid)"
query "CREATE INDEX v_devices_device_enabled ON v_devices (device_enabled)"
query "CREATE INDEX v_devices_device_address ON v_devices (device_address)"
query "CREATE INDEX v_devices_device_username ON v_devices (device_username)"
query "CREATE INDEX v_devices_device_password ON v_devices (device_password)"
query "CREATE INDEX v_devices_device_template ON v_devices (device_template)"
query "CREATE INDEX v_devices_device_uuid_alternate_fkey ON v_devices (device_uuid_alternate)"
query "CREATE INDEX v_devices_device_user_uuid_fkey ON v_devices (device_user_uuid)"
query "CREATE INDEX v_device_lines_domain_uuid_fkey ON v_device_lines (domain_uuid)"
query "CREATE INDEX v_device_lines_device_uuid_fkey ON v_device_lines (device_uuid)"
query "CREATE INDEX v_device_lines_user_id ON v_device_lines (user_id)"
query "CREATE INDEX v_device_lines_line_number ON v_device_lines (line_number)"
query "CREATE INDEX v_device_settings_domain_uuid_fkey ON v_device_settings (domain_uuid)"
query "CREATE INDEX v_device_settings_device_uuid_fkey ON v_device_settings (device_uuid)"
query "CREATE INDEX v_device_settings_device_setting_enabled ON v_device_settings (device_setting_enabled)"
query "CREATE INDEX v_fax_queue_domain_uuid_fkey ON v_fax_queue (fax_status)"
query "CREATE INDEX v_fax_queue_fax_status ON v_fax_queue (domain_uuid)"
query "CREATE INDEX v_fax_queue_insert_date ON v_fax_queue (insert_date)"
query "CREATE INDEX v_email_queue_domain_uuid_fkey ON v_email_queue (domain_uuid)"
query "CREATE INDEX v_email_queue_email_status ON v_email_queue (email_status)"
query "CREATE INDEX v_email_queue_insert_date ON v_email_queue (insert_date)"
query "CREATE INDEX v_mail_queue_attachments_email_queue_uuid_fkey ON v_email_queue (email_queue_uuid)"
query "CREATE INDEX v_mail_queue_attachments_domain_uuid_fkey ON v_email_queue (domain_uuid)"
query "CREATE INDEX v_event_guard_logs_log_date ON v_event_guard_logs (log_date)"
query "CREATE INDEX v_event_guard_logs_filter ON v_event_guard_logs (filter)"
query "CREATE INDEX v_event_guard_logs_ip_address ON v_event_guard_logs (ip_address)"
query "CREATE INDEX v_event_guard_logs_log_status ON v_event_guard_logs (log_status)"
query "CREATE INDEX v_event_guard_logs_insert_date ON v_event_guard_logs (insert_date)"
query "CREATE INDEX v_database_transactions_domain_uuid_fkey ON v_database_transactions (domain_uuid)"
query "CREATE INDEX v_database_transactions_user_uuid_fkey ON v_database_transactions (user_uuid)"
query "CREATE INDEX v_database_transactions_app_name ON v_database_transactions (app_name)"
query "CREATE INDEX v_database_transactions_transaction_address ON v_database_transactions (transaction_address)"
query "CREATE INDEX v_database_transactions_transaction_type ON v_database_transactions (transaction_type)"
query "CREATE INDEX v_menu_items_dialplan_menu_uuid_fkey ON v_menu_items (menu_uuid)"
query "CREATE INDEX v_menu_items_menu_item_parent_uuid_fkey ON v_menu_items (menu_item_parent_uuid)"
query "CREATE INDEX v_menu_items_uuid ON v_menu_items (uuid)"
query "CREATE INDEX v_menu_items_menu_item_order ON v_menu_items (menu_item_order)"
query "CREATE INDEX v_menu_item_groups_menu_uuid_fkey ON v_menu_item_groups (menu_uuid)"
query "CREATE INDEX v_menu_item_groups_menu_item_uuid_fkey ON v_menu_item_groups (menu_item_uuid)"
query "CREATE INDEX v_menu_languages_menu_uuid_fkey ON v_menu_languages (menu_uuid)"
query "CREATE INDEX v_menu_languages_menu_item_uuid_fkey ON v_menu_languages (menu_item_uuid)"
query "CREATE INDEX v_menu_languages_menu_language ON v_menu_languages (menu_language)"
query "CREATE INDEX v_contacts_domain_uuid_fkey ON v_contacts (domain_uuid)"
query "CREATE INDEX v_contacts_contact_parent_uuid_fkey ON v_contacts (contact_parent_uuid)"
query "CREATE INDEX v_contact_addresses_domain_uuid_fkey ON v_contact_addresses (domain_uuid)"
query "CREATE INDEX v_contact_addresses_contact_uuid_fkey ON v_contact_addresses (contact_uuid)"
query "CREATE INDEX v_contact_addresses_address_primary ON v_contact_addresses (address_primary)"
query "CREATE INDEX v_contact_phones_domain_uuid_fkey ON v_contact_phones (domain_uuid)"
query "CREATE INDEX v_contact_phones_contact_uuid_fkey ON v_contact_phones (contact_uuid)"
query "CREATE INDEX v_contact_phones_phone_primary ON v_contact_phones (phone_primary)"
query "CREATE INDEX v_contact_notes_domain_uuid_fkey ON v_contact_notes (domain_uuid)"
query "CREATE INDEX v_contact_notes_contact_uuid_fkey ON v_contact_notes (contact_uuid)"
query "CREATE INDEX v_contact_users_domain_uuid_fkey ON v_contact_users (domain_uuid)"
query "CREATE INDEX v_contact_users_contact_uuid_fkey ON v_contact_users (contact_uuid)"
query "CREATE INDEX v_contact_users_user_uuid_fkey ON v_contact_users (user_uuid)"
query "CREATE INDEX v_contact_groups_domain_uuid_fkey ON v_contact_groups (domain_uuid)"
query "CREATE INDEX v_contact_groups_contact_uuid_fkey ON v_contact_groups (contact_uuid)"
query "CREATE INDEX v_contact_groups_group_uuid_fkey ON v_contact_groups (group_uuid)"
query "CREATE INDEX v_contact_settings_domain_uuid_fkey ON v_contact_settings (domain_uuid)"
query "CREATE INDEX v_contact_settings_contact_uuid_fkey ON v_contact_settings (contact_uuid)"
query "CREATE INDEX v_contact_settings_contact_setting_enabled ON v_contact_settings (contact_setting_enabled)"
query "CREATE INDEX v_contact_relations_domain_uuid_fkey ON v_contact_relations (domain_uuid)"
query "CREATE INDEX v_contact_relations_contact_uuid_fkey ON v_contact_relations (contact_uuid)"
query "CREATE INDEX v_contact_relations_relation_contact_uuid_fkey ON v_contact_relations (relation_contact_uui)"
query "CREATE INDEX v_contact_emails_domain_uuid_fkey ON v_contact_emails (domain_uuid)"
query "CREATE INDEX v_contact_emails_contact_uuid_fkey ON v_contact_emails (contact_uuid)"
query "CREATE INDEX v_contact_emails_email_primary ON v_contact_emails (email_primary)"
query "CREATE INDEX v_contact_urls_domain_uuid_fkey ON v_contact_urls (domain_uuid)"
query "CREATE INDEX v_contact_urls_contact_uuid_fkey ON v_contact_urls (contact_uuid)"
query "CREATE INDEX v_contact_urls_url_primary ON v_contact_urls (url_primary)"
query "CREATE INDEX v_contact_times_domain_uuid_fkey ON v_contact_times (domain_uuid)"
query "CREATE INDEX v_contact_times_contact_uuid_fkey ON v_contact_times (contact_uuid)"
query "CREATE INDEX v_contact_times_user_uuid_fkey ON v_contact_times (user_uuid)"
query "CREATE INDEX v_contact_attachments_domain_uuid_fkey ON v_contact_attachments (domain_uuid)"
query "CREATE INDEX v_contact_attachments_contact_uuid_fkey ON v_contact_attachments (contact_uuid)"
query "CREATE INDEX v_contact_attachments_attachment_primary ON v_contact_attachments (attachment_primary)"
query "CREATE INDEX v_default_settings_default_setting_category ON v_default_settings (default_setting_category)"
query "CREATE INDEX v_default_settings_default_setting_subcategory ON v_default_settings (default_setting_subcategory)"
query "CREATE INDEX v_default_settings_default_setting_name ON v_default_settings (default_setting_name)"
query "CREATE INDEX v_default_settings_default_setting_value ON v_default_settings (default_setting_value)"
query "CREATE INDEX v_default_settings_default_setting_enabled ON v_default_settings (default_setting_enabled)"
query "CREATE INDEX v_default_settings_default_setting_description ON v_default_settings (default_setting_description)"
query "CREATE INDEX v_domain_settings_domain_setting_category ON v_domain_settings (domain_setting_category)"
query "CREATE INDEX v_domain_settings_domain_setting_subcategory ON v_domain_settings (domain_setting_subcategory)"
query "CREATE INDEX v_domain_settings_domain_setting_name ON v_domain_settings (domain_setting_name)"
query "CREATE INDEX v_domain_settings_domain_setting_value ON v_domain_settings (domain_setting_value)"
query "CREATE INDEX v_domain_settings_domain_setting_enabled ON v_domain_settings (domain_setting_enabled)"
query "CREATE INDEX v_domain_settings_domain_setting_description ON v_domain_settings (domain_setting_description)"
query "CREATE INDEX v_message_queue_domain_uuid_fkey ON v_message_queue (domain_uuid)"
query "CREATE INDEX v_message_queue_email_status ON v_message_queue (message_status)"
query "CREATE INDEX v_message_queue_message_type ON v_message_queue (message_type)"
query "CREATE INDEX v_message_queue_message_from ON v_message_queue (message_from)"
query "CREATE INDEX v_message_queue_message_to ON v_message_queue (message_to)"
query "CREATE INDEX v_message_queue_insert_date ON v_message_queue (insert_date)"
query "CREATE INDEX v_device_logs_domain_uuid_fkey ON v_device_logs (domain_uuid)"
query "CREATE INDEX v_device_logs_device_uuid_fkey ON v_device_logs (device_uuid)"
query "CREATE INDEX v_device_logs_timestamp ON v_device_logs (timestamp)"
query "CREATE INDEX v_xml_cdr_read_codec ON v_xml_cdr (read_codec)"
query "CREATE INDEX v_xml_cdr_remote_media_ip ON v_xml_cdr (remote_media_ip)"
query "CREATE INDEX v_xml_cdr_write_codec ON v_xml_cdr (write_codec)"
